Resources:
  ECSGraphQLFoodsService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSGraphQLFoodsAlbListener
    Properties:
      ServiceName: ecs-graphql-foods-service
      LaunchType: FARGATE
      Cluster: ${cf:graphql-ecs-infrastructure-${self:provider.stage}.ECSGraphQLClusterArn}
      DesiredCount: 1
      TaskDefinition:
        Ref: "ECSGraphQLFoodsTaskDefinition"
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            # - !GetAtt ECSGraphQLAlbSecurityGroupContainers.GroupId
            - ${cf:graphql-ecs-infrastructure-${self:provider.stage}.ECSGraphQLInternalAlbSecurityGroupContainersGroupId}
          Subnets: ['subnet-00a46ff0375febce4','subnet-0f4ab16717b56a95a']
      LoadBalancers:
        - TargetGroupArn:
            Ref: ECSGraphQLFoodsAlbTargetGroup
          ContainerPort: 3001
          ContainerName: ecs-graphql-task-foods
