Resources:
  ECSGraphQLAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: ecs-graphql-alb
      Subnets:
        - subnet-00a46ff0375febce4
        - subnet-0f4ab16717b56a95a
      Type: application
      SecurityGroups:
        - !GetAtt ECSGraphQLAlbSecurityGroup.GroupId

  ECSGraphQLInternalAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: ecs-graphql-internal-alb
      Subnets:
        - subnet-00a46ff0375febce4
        - subnet-0f4ab16717b56a95a
      Type: application
      Scheme: internal
      SecurityGroups:
        - !GetAtt ECSGraphQLInternalAlbSecurityGroup.GroupId

Outputs:
  ECSGraphQLAlbArn:
    Value:
      Ref: ECSGraphQLAlb
    Export:
      Name: ECSGraphQLAlbArn

  ECSGraphQLInternalAlbArn:
    Value:
      Ref: ECSGraphQLInternalAlb
    Export:
      Name: ECSGraphQLInternalAlbArn