Resources:
  ECSGraphQLAlb:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Name: ECSGraphQLClusterAlb
      Subnets:
        - subnet-00a46ff0375febce4
        - subnet-0f4ab16717b56a95a
        - subnet-0cbc33d4e68d52d27
      Type: application
      SecurityGroups:
        - !GetAtt ECSGraphQLAlbSecurityGroup.GroupId
  
  ECSGraphQLAlbTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      Name: ECSGraphQLAlbTargetGroup
      VpcId: vpc-01e3873fd27ed5dc1
      Protocol: HTTP
      Port: 80
      HealthCheckPath: /pin
      TargetType: ip

  ECSGraphQLAlbListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ECSGraphQLAlbTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ECSGraphQLAlb
      Port: 80
      Protocol: HTTP