Resources:
  ECSGraphQLUserService:
    Type: AWS::ECS::Service
    DependsOn:
      - ECSGraphQLUserAlbListener
    Properties:
      ServiceName: ecs-graphql-user-service
      LaunchType: FARGATE
      Cluster: ${cf:graphql-ecs-infrastructure-${self:provider.stage}.ECSGraphQLClusterArn}
      DesiredCount: 1
      TaskDefinition:
        Ref: "ECSGraphQLUserTaskDefinition"
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 0
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - ${cf:graphql-ecs-infrastructure-${self:provider.stage}.ECSGraphQLInternalAlbSecurityGroupContainersGroupId}
          Subnets: ['subnet-00a46ff0375febce4','subnet-0f4ab16717b56a95a']
      LoadBalancers:
        - TargetGroupArn:
            Ref: ECSGraphQLUserAlbTargetGroup
          ContainerPort: 3000
          ContainerName: ecs-graphql-task-user
