Resources:
  ECSGraphQLUserTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - "FARGATE"
      ExecutionRoleArn: arn:aws:iam::${self:custom.constant.ACCOUNT_ID}:role/ecsTaskExecutionRole
      Cpu: 256
      Memory: 512
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name: "ecs-graphql-task-user"
          Image: ${self:custom.constant.ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/ecs-graphql:user
          MemoryReservation: 256
          Memory: 512
          PortMappings:
            - containerPort: 3000
              Protocol: http